spring:
  datasource:
    username: Tomatos
    password: 20030503
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/study_db
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  application:
    name: spring-security-name

  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    time-zone: 'GMT+8'
  data:
    redis:
      port: 6379
      host: localhost
      password: zjlljz
      database: 0

my-mall:
  jwt:
    secret: "zjldljf2434324"
    expiration: 720000


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
