spring:
  security:
    # 如果使用springBoot配置类的方式也配置了默认用户那么YML配置优先级低于配置类
    user: # 配置默认用户
      name: "admin" # 配置默认用户的用户名, 默认值: user
      # 配置默认用户的密码, 默认值密码由spring security随机产生并输出在控制台
      # SpringSecurity必须配置加密方式, 如果不需要加密, 需要明确使用{noop} 占位符表示使用明文
      password: "{noop}111"
logging:
  level:
    # 配置 org.springframework.security 这个包下的类日志级别都是 trace
    org.springframework.security: debug